weatherapp:
  name: weatherapp
  namespace: default
  replicaCount: 2
  image:
    repository: roish1/weatherapp
    tag: latest
  service:
    type: ClusterIP
    # type: NodePort
    port: 5000
    targetPort: 5000
    # nodePort: 32300

chimensjr:
  name: chimensjr
  namespace: default
  replicaCount: 2
  image:
    repository: chimenesjr/solitaire
    tag: nginx
  service:
    type: ClusterIP
    # type: NodePort
    port: 80
    targetPort: 80
    # nodePort: 32400

configmap:
  name: weatherapp-configmap
  data:
    BG_COLOR: "#3295a8"

efs:
  name: efs-sc
  provisioner: efs.csi.aws.com
  parameters:
    provisioningMode: efs-ap
    fileSystemId: fs-0e442664d1c7da0f5
    directoryPerms: "700"