apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.chimensjr.name }}
  name: {{ .Values.chimensjr.name }}
  namespace: {{ .Values.chimensjr.namespace }}
spec:
  replicas: {{ .Values.chimensjr.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.chimensjr.name }}
  strategy:
    type: {{ .Values.chimensjr.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.chimensjr.strategy.rollingUpdate.maxSurge | quote }}
      maxUnavailable: {{ .Values.chimensjr.strategy.rollingUpdate.maxUnavailable | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.chimensjr.name }}
    spec:
      containers:
      - image: "{{ .Values.chimensjr.image.repository }}:{{ .Values.chimensjr.image.tag }}"
        name: {{ .Values.chimensjr.name }}
        ports:
        - containerPort: {{ .Values.chimensjr.service.port }}
        envFrom:
          - configMapRef:
              name: chimensjr-configmap
      topologySpreadConstraints:
      - maxSkew: {{ .Values.chimensjr.topologySpreadConstraints.maxSkew }}
        topologyKey: {{ .Values.chimensjr.topologySpreadConstraints.topologyKey }}
        whenUnsatisfiable: {{ .Values.chimensjr.topologySpreadConstraints.whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            app: {{ .Values.chimensjr.name }}