{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.chimensjr.name }}-ingress
  namespace: {{ .Values.chimensjr.namespace }}
  annotations:
    {{- with .Values.ingress.chimensjr.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.chimensjr.spec.ingressClassName }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.chimensjr.spec.rules.http.paths.path | quote }}
            pathType: {{ .Values.ingress.chimensjr.spec.rules.http.paths.pathType }}
            backend:
              service:
                name: {{ .Values.chimensjr.name }}-service
                port:
                  number: {{ .Values.chimensjr.service.port }}
{{- end }}