apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.weatherapp.namespace }}
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi