apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.weatherapp.namespace }}
  name: {{ .Values.weatherapp.pvc.name }}
spec:
  accessModes:
    - {{ .Values.weatherapp.pvc.accessModes }}
  storageClassName: {{ .Values.efs.name }}
  resources:
    requests:
      storage: {{ .Values.weatherapp.pvc.resources.requests.storage }}