{{- if .Values.efs.enabled }}
{{- if not .Values.efs.parameters.fileSystemId }}
{{- fail "efs.parameters.fileSystemId is required. Please provide the EFS filesystem ID." }}
{{- end }}

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: {{ .Values.weatherapp.namespace }}
  name: {{ .Values.efs.name }}
provisioner: {{ .Values.efs.provisioner }}
parameters:
  provisioningMode: {{ .Values.efs.parameters.provisioningMode }}
  fileSystemId: {{ .Values.efs.parameters.fileSystemId }}
  directoryPerms: {{ .Values.efs.parameters.directoryPerms | quote }}
  region: {{ .Values.efs.parameters.region }}
reclaimPolicy: Delete
volumeBindingMode: Immediate

{{- end }}