apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Values.weatherapp.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.weatherapp.service.port }}
      targetPort: {{ .Values.weatherapp.service.targetPort }}
      # nodePort: {{ .Values.weatherapp.service.nodePort }}
  type: {{ .Values.weatherapp.service.type }}