apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.weatherapp.namespace }}
  name: {{ .Values.configmap.weatherapp.name }}
data:
  BG_COLOR: {{ .Values.configmap.weatherapp.data.BG_COLOR | quote }}
