apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.weatherapp.namespace }}
  name: {{ .Values.configmap.weatherapp.name }}
data:
  BG_COLOR: {{ .Values.configmap.weatherapp.data.BG_COLOR | quote }}
  KEY: {{ .Values.configmap.weatherapp.data.KEY | quote }}
  SECRET_NAME: {{ .Values.configmap.weatherapp.data.SECRET_NAME | quote }}
  AWS_REGION: {{ .Values.configmap.weatherapp.data.AWS_REGION | quote }}