name: Update Chart Color

on:
  workflow_dispatch:
    inputs:
      newColor:
        description: 'New color value (e.g., "#RRGGBB")'
        required: true
        default: '#3295a8'

jobs:
  update-color:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update color in values.yaml
        run: |
          # Define file path
          VALUES_FILE="weatherapp/values.yaml"
          
          # Check if file exists
          if [ ! -f "$VALUES_FILE" ]; then
            echo "Error: values.yaml file not found at $VALUES_FILE"
            exit 1
          fi
          
          # Update the color value using yq (YAML processor)
          echo "Installing yq..."
          sudo apt-get install -y yq
          
          echo "Updating color value..."
          yq eval '.configmap.data.BG_COLOR = "'"${{ github.event.inputs.newColor }}"'"' $VALUES_FILE > temp.yaml && mv temp.yaml $VALUES_FILE
          
          # Display the change
          echo "Updated values.yaml:"
          cat $VALUES_FILE | grep -A2 "configmap:"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update chart color to ${{ github.event.inputs.newColor }}"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
