name: Update Chart Color

on:
  workflow_dispatch:
    inputs:
      newColor:
        description: 'New color value (e.g., "#RRGGBB")'
        required: true
        default: '#3295a8'

jobs:
  update-color:
    runs-on: ubuntu-latest
    # This permissions block is CRUCIAL
    permissions:
      contents: write  # Gives GITHUB_TOKEN permission to push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This ensures subsequent git commands will authenticate properly
          persist-credentials: true

      - name: Update color in values.yaml
        run: |
          VALUES_FILE="weatherapp/values.yaml"
          
          if [ ! -f "$VALUES_FILE" ]; then
            echo "Error: values.yaml file not found at $VALUES_FILE"
            exit 1
          fi
          
          echo "Installing yq..."
          sudo apt-get install -y yq
          
          echo "Updating color value..."
          yq eval '.configmap.data.BG_COLOR = "'"${{ github.event.inputs.newColor }}"'"' "$VALUES_FILE" > temp.yaml && mv temp.yaml "$VALUES_FILE"
          
          echo "Updated values.yaml:"
          cat "$VALUES_FILE" | grep -A2 "configmap:"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update chart color to ${{ github.event.inputs.newColor }}"
          git push