name: Update Chart Version

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New chart version (e.g., "1.2.3")'
        required: true
        default: '0.1.0'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Gives GITHUB_TOKEN permission to push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Update version in Chart.yaml
        run: |
          CHART_FILE="weatherapp/Chart.yaml"
          
          if [ ! -f "$CHART_FILE" ]; then
            echo "Error: Chart.yaml file not found at $CHART_FILE"
            exit 1
          fi
          
          echo "Installing yq..."
          sudo apt-get install -y yq
          
          echo "Updating version..."
          yq eval '.version = "'"${{ github.event.inputs.newVersion }}"'"' "$CHART_FILE" > temp.yaml && mv temp.yaml "$CHART_FILE"
          
          echo "Updated Chart.yaml:"
          cat "$CHART_FILE" | grep "version:"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update chart version to ${{ github.event.inputs.newVersion }}"
          git push